
stocks_to_download = [
    {"ticker": "^IBEX", "name": "ibex35"},
    {"ticker": "^GSPC", "name": "s_p500"},
    {"ticker": "^GDAXI", "name": "dax"},
    {"ticker": "^N100", "name": "euro_next100"},
    {"ticker": "^N225", "name": "nikkei225"},
    {"ticker": "^FTSE", "name": "ftse100"},
    {"ticker": "^VIX", "name": "volatility_index"},
    {"ticker": "EURUSD=X", "name": "euro_dollar"},
    {"ticker": "GC=F", "name": "gold"},
    {"ticker": "CL=F", "name": "oil"}
]

ibex_selected_companies = [
    {"ticker": "ANA.MC", "name": "Acciona", "sector": "Infraestructuras"},
    {"ticker": "ANE.MC", "name": "Acciona Energía", "sector": "Energia"},
    {"ticker": "ACX.MC", "name": "Acerinox", "sector": "Siderurgia"},
    {"ticker": "ACS.MC", "name": "ACS", "sector": "Construcción"},
    {"ticker": "Aena.MC", "name": "Aena", "sector": "Infraestructuras"},
    {"ticker": "AMS.MC", "name": "Amadeus", "sector": "Información y comunicaciones"},
    {"ticker": "MTS.MC", "name": "ArcelorMittal", "sector": "Siderurgia"},
    {"ticker": "BBVA.MC", "name": "BBVA", "sector": "Banca"},
    {"ticker": "SAB.MC", "name": "Banco Sabadell", "sector": "Banca"},
    {"ticker": "BKT.MC", "name": "Bankinter", "sector": "Banca"},
    {"ticker": "CABK.MC", "name": "CaixaBank", "sector": "Banca"},
    {"ticker": "CLNX.MC", "name": "Cellnex Telecom", "sector": "Información y comunicaciones"},
    {"ticker": "ENG.MC", "name": "Enagás", "sector": "Energía"},
    {"ticker": "ELE.MC", "name": "Endesa", "sector": "Energía"},
    {"ticker": "FER.MC", "name": "Ferrovial", "sector": "Construcción"},
    {"ticker": "FDR.MC", "name": "Fluidra", "sector": "Wellness"},
    {"ticker": "GRF.MC", "name": "Grifols", "sector": "Biotecnología"},
    {"ticker": "IAG.MC", "name": "International Airlines Group", "sector": "Aerolíneas"},
    {"ticker": "IBE.MC", "name": "Iberdrola", "sector": "Energía"},
    {"ticker": "ITX.MC", "name": "Inditex", "sector": "Retail/Moda"},
    {"ticker": "IDR.MC", "name": "Indra", "sector": "Información y comunicaciones"},
    {"ticker": "COL.MC", "name": "Colonial", "sector": "Inmobiliaria"},
    {"ticker": "LOG.MC", "name": "Logista", "sector": "Logística"},
    {"ticker": "MAP.MC", "name": "MAPFRE", "sector": "Seguros"},
    {"ticker": "MRL.MC", "name": "Merlin Properties", "sector": "Inmobiliaria"},
    {"ticker": "NTGY.MC", "name": "Naturgy", "sector": "Energía"},
    {"ticker": "PUIG.MC", "name": "Puig Brands", "sector": "Actividades de las sociedades holding"},
    {"ticker": "REE.MC", "name": "Redeia", "sector": "Energía"},
    {"ticker": "REP.MC", "name": "Repsol", "sector": "Energía"},
    {"ticker": "ROVI.MC", "name": "Rovi", "sector": "Biotecnología"},
    {"ticker": "SCYR.MC", "name": "Sacyr", "sector": "Construcción"},
    {"ticker": "SAN.MC", "name": "Santander", "sector": "Banca"},
    {"ticker": "SLR.MC", "name": "Solaria", "sector": "Energía"},
    {"ticker": "TEF.MC", "name": "Telefónica", "sector": "Información y comunicaciones"},
    {"ticker": "UNI.MC", "name": "Unicaja Banco", "sector": "Banca"},
    {"ticker": "MEL.MC", "name": "Meliá Hotels", "sector": "Turismo"},
    {"ticker": "PHM.MC", "name": "PharmaMar", "sector": "Biotecnología"},
    {"ticker": "ALM.MC", "name": "Almirall", "sector": "Biotecnología"},
    {"ticker": "CIE.MC", "name": "CIE Automotive", "sector": "Automoción"},
    {"ticker": "SGRE.MC", "name": "Siemens Gamesa", "sector": "Energía"},
    {"ticker": "VIS.MC", "name": "Viscofan", "sector": "Alimentación"},
    {"ticker": "RCI.MC", "name": "Renta Corporación", "sector": "Inmobiliaria"},
    {"ticker": "SNG.MC", "name": "Soltec", "sector": "Energía"}
    # Sustituye o completa tickers actuales según BME
]
